### ISSUE TITLE
ABE doesn´t work on Seti Astro Suite Pro v 1.3.20 in Intel Mac

### ISSUE THREAD

**Issue by mrvivar** [setiastro/setiastrosuitepro#19]
Hi. Automatic Background Extractor gave me this error message.

TypeError: asarray() got an unexpected keyword argument 'copy'

Details :
Traceback (most recent call last):
  File "setiastrosuitepro.py", line 3975, in _open_abe_tool
  File "pro/abe.py", line 558, in __init__
  File "pro/abe.py", line 633, in _populate_initial_preview
  File "pro/abe.py", line 783, in _set_preview_pixmap
TypeError: asarray() got an unexpected keyword argument 'copy'

Thank you for all this great job.
